{
 "title": "Dash 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "# Contracts - Last 24 hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(contract_api_histogram_count[24h])"
    }
   ]
  },
  {
   "title": "Total - Last 24 hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(contract_api_histogram_sum[24h])"
    }
   ]
  },
  {
   "title": "Mean tickets - Last 24 hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(contract_api_histogram_sum[24h])/increase(contract_api_histogram_count[24h])"
    }
   ]
  },
  {
   "title": "# Contracts - Last Month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(contract_api_histogram_count[30d])"
    }
   ]
  },
  {
   "title": "Total - Last Month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(contract_api_histogram_sum[30d])"
    }
   ]
  },
  {
   "title": "Mean tickets - Last Month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(contract_api_histogram_sum[30d])/increase(contract_api_histogram_count[30d])"
    }
   ]
  },
  {
   "title": "# Contracts - Cumulative",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "contract_api_histogram_count" }
   ]
  },
  {
   "title": "Total - Cumulative",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "contract_api_histogram_sum" }
   ]
  },
  {
   "title": "Mean tickets - Cumulative",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "contract_api_histogram_sum/contract_api_histogram_count"
    }
   ]
  },
  {
   "title": "# Contracts - Last Hour (Test)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(contract_api_histogram_count[1h])"
    }
   ]
  },
  {
   "title": "Total - Last Hour (Test)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(contract_api_histogram_sum[1h])"
    }
   ]
  },
  {
   "title": "Mean tickets - Last Hour (Test)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(contract_api_histogram_sum[1h])/increase(contract_api_histogram_count[1h])"
    }
   ]
  }
 ]
}